# Access via "http://localhost:8080"
services:
  mediawiki:
    build: ./towhouwiki
    container_name: touhouwiki
    restart: always
    ports:
      - 8080:80
    links:
      - database
    environment:
      TOUHOUWIKI_ENV: DEV
    volumes:
      - images:/var/www/html/images
      - ${PWD}/SecureSettings.php:/var/www/SecureSettings.php
  database:
    image: mariadb:10.11-jammy
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: touhouwiki
      MYSQL_USER: touhouwiki
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  images:
  db:
