<?php
# This file was automatically generated by the MediaWiki 1.17alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.

require_once("/var/www/touhouwiki.net/htdocs/CommonSettings.php");

# Let's try forcing the DB over to PG and see what breaks

## Database settings
#$wgDBtype           = "postgres";
#$wgDBserver         = "cirno.lunar-tokyo.net";
#$wgDBname           = "touhouwiki";
#$wgDBuser           = "wiki";
#$wgDBpassword       = "OhCh3Fiy";
#$wgDBport	    = "5433";
#$wgDBmwschema       = "touhouwiki";

# Continue

$wgSitename         = "Touhou Wiki";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/common/images/alicelogo.png";

#MySQL specific settings
#$wgDBprefix         = "touhouwiki_";

# Site language code, should be one of ./languages/Language(.*).php
$wgLanguageCode = "en";

/*
# Log File
$wgDebugLogFile = "/usr/vhosts/touhouwiki/TEST-debug_log.txt";
# Profiler
// Only record profiling info for pages that took longer than this
$wgProfileLimit = 5.0;
// Don't put non-profiling info into log file
$wgProfileOnly = false;
// Log sums from profiling into "profiling" table in db
$wgProfileToDatabase = false;
// If true, print a raw call tree instead of per-function report
$wgProfileCallTree = false;
// Should application server host be put into profiling table
$wgProfilePerHost = true;
// Settings for UDP profiler
$wgUDPProfilerHost = '127.0.0.1';
$wgUDPProfilerPort = '3811';
// Detects non-matching wfProfileIn/wfProfileOut calls
$wgDebugProfiling = false;
// Output debug message on every wfProfileIn/wfProfileOut
$wgDebugFunctionEntry = 0;
// Lots of debugging output from SquidUpdate.php
$wgDebugSquid = false;
// Timestamps
$wgDebugTimestamps = true;
*/

// Please tell me why Scribunto/{{#invoke}} is broken
// ANSWER: MW 1.20 required.
$wgShowExceptionDetails = true;
